---
title: "First Draft"
date: "2025-02-26"
categories: [narrative, assets, design]
image: "../../images/narr_seq.svg"
---

The latest narrative script is available [here](/narrative_script.html).

After a lot of work, the first draft is completed and ready to be put into the game which will be my next focus. I'm satisfied with the work so far and all of the events are ready. I could have used more time to flesh some of these out but due to time constraints, I need to move along to narrative implementation for now. I'm hoping to revisit this in the near future to maybe add some more depth and see if I can squeeze another event or two into the game.

# Writer's Block

I'm not much of a writer, technical work has always been my specialty. This is very much a first for me. Feels like I'm in the deep end. I found myself stuck for words or at a loss of what I wanted my dialogue to achieve.

Unable to write meant my motivation was waning, especially when I just wanted to get stuck into the code instead. The fact that i used a sequence diagram instead of a storyboard for the narrative highlights this.

On multiple occasions, I got stuck, unable to write anything more, but the clock keeps ticking. Deadlines are looming. There is no rest for the wicked after all. As I write this entry, I reflect on all of those times. By persevering, I overcame a problem I never expected to have.

As hoped, this has pushed boundaries of my understanding in an attempt to make me more creative. I'm not sure I succeeded, only user testing can tell me that. For now, I am satisfied with my hard work. My only worry now is that my hard work isn't enough. I may fail in which case I'll revise my writing and try again.

# Inspirations

I had two major inspirations for the game events so far. There were more books but these ones struck me as the gems I needed for this project. They are described below.

## A field guide to Irish Fairies by Curran, B. and Whitson, A

This is a pocket-sized book with excellent descriptions. It sits at the core of what I believe the creatures might act like. The descriptions are easy to grasp and understand, making it a great introduction for any of the creatures I was learning about.

## The Faerie Isle: Tales and Traditions of Ireland’s Forgotten Folklore by Quinn, S

This book is similar to the one described above but it's a lot more visually stunning. I used it as a cross reference against the book above to make sure the information I had seemed correct. Tales and Folklore tend to evolve with time and comparing and contrasting these two was a great tool to make sure I was getting crucial information right.



