---
title: "Game Script"
about:
  template: solana
---

# Introductions

### **INT. GYM - DAY - TRIGGER: Character Creation Completed**

Plays after the character creation acting as a tutorial for the game while introducing the PLAYER to ST. PADDY, their new job and the banshee. The PLAYER is limited to working at this time.

<center>
***PLAYER***

<span style="color:SlateGray">*Finally arrived, Uncle Colin really pulled through for me here. Not sure I could have landed this gig without him. Better make sure to thank him soon, 'tis been hard the last few weeks.*</span>

***ST. PADDY***

Ahh you finally made it.
The name is Paddy. I'm the manager of this here Gym. Tír na Sioga we call it.

***PLAYER***

I'm {{NAME}}, thank you for taking me on on such short notice.

***ST. PADDY***

Looking forward to having you on board.

Colin said it's your first time coming to Inishsióg.

Good chap that one, what are your thoughts on the place so far? We have some good folk here, I'm sure you'll all get along.

***PLAYER***

<span style="color:SlateGray">*Land of the Fairies on Fairy Island, what a name! I hope this place isn't filled with nutcases.*</span>

Only had a quick look around after the boat from Galway arrived. Seems nice and quaint island.

***ST. PADDY***

It's about time we get some help around here.

Grand let's put you right to work so.

***PLAYER***

<span style="color:SlateGray">*Need to put my best foot forward here, can't put this opportunity to waste.*</span>

Sounds good, where should I start?

***ST. PADDY***

Grand, you're going to work with some fairly odd folk here but they are good at heart.

All you need to do is chat and work out with them. You'll get paid for any day or night shift ya take on.

Make sure to treat them well, they need good people to spend some time with.

***PLAYER***

<span style="color:SlateGray">*Ugh, I was hoping for a more low key role here. Blending in with the wall paper would be nice. Meeting new people is a real tough ask but I can't let my family down again*</span>

Ok, I'll do my best.

***ST. PADDY***

You sure your up for this? You seem a bit pale.

***PLAYER***

Yep, leave it to me!

***ST. PADDY***

Alright, we don't many people often. It's rare to see more than one person come in.

Seems like today Chaointe Doran dropped by. Shes a timid spirit that struggles with conversation but she really likes to talk.

If you take it slow I'm sure she'll warm up to you in no time.

***PLAYER***

<span style="color:SlateGray">*Wow shes a looker but she does seem fidgety about my presence here. If paddy didn't point her out I'm not sure I'd have seen here. Her presence seems so faint*</span>

***ST. PADDY***

The people she gets to know don't stick around for long so take care to be a good attentive person she can lean on.

***PLAYER***

<span style="color:SlateGray">*The way he said that last part sent chills down my spine, 'tis odd but it can't be that bad right?*</span>

***ST. PADDY***

Your job today is to go help her out with her workout. Am countin' on ya, good luck kid.

Take care now, am off to cater my pride and joy so. Oh Paddy's Pub well make you great again now that I have more time.

***PLAYER***

<span style="color:SlateGray">*Paddy waddled off humming such a joyful tune, I wonder what it was. Alright time to get to it. It's not like Chaointe bites right?!*</span>

</center>

The next day they will have choice of where they want to head during the day.

</br>

### **INT. GYM - DAY/NIGHT - TRIGGER: Entered the gym to work a second time**

The Player enters the Gym to work for a second time. St. Paddy introduces the second character who is a pooka.

<center>

***ST. PADDY***

Welcome back, good to have ya here again. Ready for another day at work. You can either meet the banshee again or go to work.

***PLAYER***

<span style="color:SlateGray">*He sounds way too happy to see me. Something tells me hes about to run off again and leave me to deal with the shortie in the corner.*</span>

Aye Aye Captain!

***ST. PADDY***

Lovely enthusiasm, I see your already staring down Monsieur Púca Cleasaí.

Ya know its rude to stare right, tho he'd do the same. All I can do is hope your not two peas in a pod.

He's a bit of a trickster, whatever you do don't let him push you about ok.

***PLAYER***

<span style="color:SlateGray">*I nodded back at Paddy and wondered if this guy might be a kindred spirit*</span>

***ST. PADDY***

With this one you have to make sure you don't let the peer pressure get to you. Don't want to do things you'll regret after all.

If your not up for this your always free to leave and come back another day.

Alright, am off to my home sweet home for a pint.

***PLAYER***

<span style="color:SlateGray">*What a man, so much joy but hes only got the pub on his mind. I wonder if I'll ever have a place like that.*</span>

See you soon boss!
</center>

You now have the choice of working or doing something else entirely. Waking into a location will not lock you out of doing other things anymore.

</br>

### **INT. GYM - DAY/NIGHT - TRIGGER: Entered the gym to work a third time**

The Player enters the Gym to work for a third time. St. Paddy introduces the third character who is a dullahan. The scene is a bit tense as this is is the first time the player outright finds out the people here aren't human.

<center>

***PLAYER***

Ahhh, T-that parson's h-head i-is...

<span style="color:SlateGray">*Before I could finish my sentence, Paddy put his hand over my mouth to stop me. All I could see was the severed head glaring at me from a distance.*</span>

***ST. PADDY***

C'mere to me, whatever your about to yell stuff it down deep and don't. We don't need this beautiful day going arseways.

***PLAYER***

<span style="color:SlateGray">*I gulped holding my fear back. Paddy's demeanour shifted from the usual happy go lucky caring self. What is this, should I leg it while I still can?*</span>

***ST. PADDY***

Calm down kid, I'm sure you've realised it by know. Everyone who comes here ain't exactly human but they are good people.

Our little lady over there is the headless rider herself, Corm Dubh. Try not to cross her as she has a tenancy for violence.

***PLAYER***

<span style="color:SlateGray">*Paddy is right, I already knew this place was odd. Knowing I'm not seeing a dead body has put me slightly at ease.*</span>

***ST. PADDY***

Yeah you'll be fine. Today might be a tough day on the job but you've got this after all you already meet some inhuman guests of ours. Just make sure to apologize for that outburst.

***PLAYER***

<span style="color:SlateGray">*I guess I'm gonna need to figure out whats up with this town. It's so odd that I may just fit right in. These misfits may be my kind of odd but should i really be here?*</span>

W-will do. Sorry for making things uncomfortable.

***ST. PADDY***

'Tis grand, reflecting on and rectifying our mistakes is important.

I'll leave ya to it so. Am off to take care of da pub.

***PLAYER***

<span style="color:SlateGray">*No humming today. I really soured the mood. Not a great way to start another day on the job. I should at least go and apologize*</span>

</center>
</br>

# Player Events

### **INT. HOME - MORNING - TRIGGER: Morning after meeting the banshee**
The PLAYER reflects on their meeting with CHAOINTE.

#### Good Choice
<center>

***PLAYER***

<span style="color:SlateGray">*I woke up early with my muscles aching from the exercise. It feels good to have exercised yesterday. The sleep felt so much better than usual.*</span>

<span style="color:SlateGray">*Chaointe was so nice. I should make sure exercise with her again soon. I really got to learn more from her if I'm going to do a good job at the gym.*</span>

<span style="color:SlateGray">*Alright time to put this new found energy to good use. Should I go to work or visit the town? Paddy doesn't seem to mind which shifts I take.*</span>

</center>

#### Bad Choice
<center>

***PLAYER*** 

<span style="color:SlateGray">*I woke up early with my muscles aching from the exercise. My sleep was awful and I'm aching so much*</span>

<span style="color:SlateGray">*I still feel weird about the interaction I've had with Chaointe. Maybe I can still make it up to her*</span>

<span style="color:SlateGray">*Ehhh, I guess I should get up and try to go to work. The parents would be so disappointing If I failed at another job. I wouldn't be able to face uncle Colin after this either.*</span>

</center>

### **INT. HOME - MORNING - TRIGGER: Morning after meeting the pooka**
The PLAYER reflects on their meeting with PUCA.

#### Good Choice
<center>
</center>
</br>

#### Bad Choice

<center>
*Not to judge but he looks kinda like a garden gnome.*
</center>
</br>

### **INT. HOME - MORNING - TRIGGER: Morning after meeting the dullaghan**
The PLAYER reflects on their meeting with Crom.

#### Good Choice
<center>
</center>
</br>

#### Bad Choice

<center>
</center>
</br>

### **INT. HOME - MORNING - TRIGGER: On completing 1/3 of the character events**

The PLAYER has well and truly accepted their role at the gym. It's starting to seem like they may have found a place where they belong. The PLAYER and ST. PADDY have a chat with some banter while PADDY checks in on the PLAYER.

<center>

</center>
</br>

### **INT. HOME - MORNING - TRIGGER: On completing 1/2 of the character events**

The PLAYER meets paddy they catch up. They discuss the players success so far but conflict arises as ST. PADDY is looking to retire and move on from managing the gym.

<center>

</center>
</br>

### **INT. HOME - MORNING - TRIGGER: On completing 2/3 of the character events**

The retirement is looming. The PLAYER and ST. PADDY have a heated discussion about the gym. The PLAYER is willing to take over but PADDY is not sure if a changeling is fit for the job revealing the main characters true nature. Doubt settles in and the conflict is at its peak. The players past is also revealed.

<center>

</center>
</br>

### **INT. HOME - MORNING - TRIGGER: On completing all character endings**

On successful completion of all character events without bad endings, The PLAYER and ST. PADDY meet once more. PADDY is impressed with the players determination to help others and decides that the PLAYER is fit to take over. The story comes to a close.

<center>

</center>
</br>

# Banshee Events - Chaointe Doran

The banshees name is Chaointe Doran. It roughly translates to Lamenting Wonderer.

### **INT. GYM - DAY - TRIGGER: First Day At Work**
<center>

***PLAYER***

Hey, my name is {{NAME}}. I'm new here. how can I help you today?

***CHAOINTE***

H-Hi, I-i'm C-Chaointe Doran. It's nice to meet you {{NAME}}. I'm here to work out. W-would you like to join me please?

***PLAYER***

Yeah sure.

<span style="color:SlateGray">*We started our workout. An uncomfortable silence loomed over us and the exercising feels excruciating. Chaointe is fidgety and looks like she has something to say but isn't. I should break the silence.*</span>

</center>

#### **PLAYER CHOICE:** As I keep doing I blurt out:

##### **A.** This exercise is tough, how are you managing?

<center>

***CHAOINTE***

I'm doing well b-but you seem to be struggling a bit. Y-Your form is off. You don't do this often do you?

***PLAYER***

Yeah your right, I don't work out much so I may not be the best option to look after this place.

***CHAOINTE***

Don't worry, it will take some effort but I'm sure you'll improve in no time.

***PLAYER***

<span style="color:SlateGray">*Chaointe helped me improve my form and as we continued to exercise it was exhausting but it felt much better.*</span>

Thanks so much, this feels a lot better now.

***CHAOINTE***

N-no problem. Thanks for working out with me. L-let's do it again soon.

***PLAYER***

Looking forward to it. See you soon.

<span style="color:SlateGray">*Chaointe left with a spring in her step. I finish cleaning up and head home to sleep*</span>

</center>

##### **B.** Whats up? Spit it out already!

<center>

***CHAOINTE***

I-it's n-nothing. I'm so s-sorry.

***PLAYER***

No need to apologize. Let's keep working.

<span style="color:SlateGray">*The awkward silence continued for the remainder of the workout. I'm exhausted and aching all over*</span>

Phew, It's good to be done.

***CHAOINTE***

Y-yeah, I need to head off now. Bye.

***PLAYER***

<span style="color:SlateGray">*Chaointe left swiftly leaving you wondering what she had to say. I finish cleaning up and head home to sleep*</span>

</center>

</br>

### **INT. PUB - Night - TRIGGER: First event completed**
<center>

</center>
</br>

### **INT. CAFE - DAY - TRIGGER: Second event completed, Met Pooka**
<center>

</center>
</br>

### **INT. GYM - DAY/NIGHT - TRIGGER: Third event completed, Met Dullahan**
<center>

</center>
</br>

### **EXT. STREET - NIGHT (Forced) - TRIGGER: Fourth event completed, Friendship Threshold Reached**
<center>

</center>
</br>

### **EXT. STREET - NIGHT (Forced) - TRIGGER: Fourth event completed, Friendship Threshold Not Reached**
<center>

</center>
</br>

# Pooka Events - Púca Cleasaí

The pookas name is Púca Cleasaí. It roughly translates to Goblin Trickster.

### **INT. GYM - DAY/NIGHT - TRIGGER: Second Day At Work**
<center>

</center>
</br>

### **INT. RESTAURANT - DAY - TRIGGER: First event completed**
<center>

</center>
</br>

### **INT. GYM - DAY/NIGHT - TRIGGER: Second event completed, Met Dullahan**
<center>

</center>
</br>

### **INT. RESTAURANT - DAY - TRIGGER: Third event completed**
<center>

</center>
</br>

### **INT. FOREST - NIGHT (Forced) - TRIGGER: Fourth event completed, Friendship Threshold Reached**
<center>

</center>
</br>

### **INT. FOREST - NIGHT (Forced) - TRIGGER: Fourth event completed, Friendship Threshold Not Reached**
<center>

</center>
</br>

# Dullahan Events - Crom Dubh

The dullahans name is Crom Dubh as its known the be the Embodiment of this Celtic God.

### **INT. GYM - DAY/NIGHT - TRIGGER: Third Day At Work**
<center>

</center>
</br>

### **INT. PUB - NIGHT - TRIGGER: First event completed**
<center>

</center>
</br>

### **INT. GYM - DAY/NIGHT - TRIGGER: Second event completed**
<center>

</center>
</br>

### **INT. PUB - NIGHT - TRIGGER: Third event completed**
<center>

</center>
</br>

### **EXT. STREET - NIGHT (Forced) - TRIGGER: Fourth event completed, Friendship Threshold Reached**
<center>

</center>
</br>

### **EXT. STREET - NIGHT (Forced) - TRIGGER: Fourth event completed, Friendship Threshold Not Reached**
<center>

</center>
</br>


# References
- Curran, B. and Whitson, A. (2007) A field guide to Irish Fairies. Belfast: Appletree Press.
- Quinn, S. (2024) The Faerie Isle: Tales and Traditions of Ireland’s Forgotten Folklore. London: Walker Books Ltd.
- Jackson, J.K. and Fitzgerald, K. (2022) Irish folk & fairy tales: Fables, folklore & ancient stories. London: Flame Tree Publishing.
- Yeats, W.B. (1888) Irish fairy tales and Folklore. New York, NY: Clydesdale Press.

